"""
Django settings for weakauras_web project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import yaml
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Load configuration from token.yml with fallback locations
def load_bot_config():
    """Load bot configuration from token.yml with fallback locations."""
    # Fallback paths to check for bot config (same as main.py)
    fallback_paths = [
        Path("~/.config/weakauras-bot/token.yml").expanduser(),
        Path("~/weakauras-bot-config/token.yml").expanduser(),
        BASE_DIR.parent / "discord-bot" / "settings" / "token.yml",
    ]

    for config_path in fallback_paths:
        if config_path.exists():
            try:
                with open(config_path) as f:
                    return yaml.safe_load(f)
            except (yaml.YAMLError, KeyError, TypeError):
                continue

    # Return empty config if none found
    return {}


# Load bot configuration
_bot_config = load_bot_config()

# Environment detection - check for DJANGO_ENV or fall back to development
ENVIRONMENT = os.getenv("DJANGO_ENV", "dev")


# Bot data directory (shared with the Discord bot)
def load_bot_data_dir():
    """Load bot data directory from configuration with fallback locations."""
    data_dir_name = _bot_config.get("storage", {}).get("data_directory", "server_data")

    # Check if it's an absolute path or contains ~ (home directory)
    if data_dir_name.startswith(("/", "~")):
        # Absolute path or home directory - expand ~ and use as-is
        return Path(data_dir_name).expanduser().resolve()

    # Relative path - make it relative to the bot package location
    bot_package_dir = BASE_DIR.parent / "discord-bot"
    return bot_package_dir / data_dir_name


BOT_DATA_DIR = load_bot_data_dir()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
# Load SECRET_KEY from token.yml configuration based on environment
def get_secret_key():
    """Get Django SECRET_KEY from configuration with environment support."""
    django_config = _bot_config.get("django", {})
    secret_keys = django_config.get("secret_keys", {})

    # Try to get environment-specific secret key
    secret_key = secret_keys.get(ENVIRONMENT)

    if not secret_key:
        # Fallback to single secret_key for backward compatibility
        secret_key = django_config.get("secret_key")

    if not secret_key:
        if ENVIRONMENT == "dev":
            # Allow default SECRET_KEY for development/CI environments
            return "django-insecure-dev-default-key-not-for-production"

        msg = (
            f"Django SECRET_KEY is required for '{ENVIRONMENT}' environment. "
            f"Add 'django.secret_keys.{ENVIRONMENT}' to your token.yml configuration."
        )
        raise ValueError(msg)

    return secret_key


SECRET_KEY = get_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # Third party apps
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.discord",
    "rest_framework",
    # Local apps
    "authentication",
    "macros",
    "servers",
    "shared",
    "user_stats",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "weakauras_web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "weakauras_web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django sites framework
SITE_ID = 1

# Django allauth configuration
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Login/logout URLs
LOGIN_URL = "/accounts/login/"
LOGOUT_URL = "/accounts/logout/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

# Allauth settings - Discord OAuth only
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_QUERY_EMAIL = True

# Modern allauth settings (replaces deprecated EMAIL_REQUIRED/USERNAME_REQUIRED)
ACCOUNT_SIGNUP_FIELDS = []  # No signup fields needed - Discord OAuth only

# Use custom social account adapter but keep default account adapter
SOCIALACCOUNT_ADAPTER = "authentication.adapters.DiscordOnlySocialAccountAdapter"
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"

# Force Discord OAuth only - disable regular signup/login
ACCOUNT_SIGNUP_REDIRECT_URL = "/dashboard/"
ACCOUNT_LOGIN_ON_GET = False

# Auto-connect social accounts
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_LOGIN_ON_GET = True

# Discord OAuth settings (will be loaded from bot config)
SOCIALACCOUNT_PROVIDERS = {
    "discord": {
        "SCOPE": ["identify", "guilds"],
        "AUTH_PARAMS": {"response_type": "code"},
        "VERIFIED_EMAIL": False,  # Discord email verification not required
    }
}

# Ensure tokens are stored
SOCIALACCOUNT_STORE_TOKENS = True

# Static files configuration
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Discord OAuth credentials are configured in the database via SocialApp model
# No need to load from YAML - this was causing conflicts

# Django Messages Configuration
# Map Django message levels to Bootstrap alert classes
MESSAGE_TAGS = {
    messages.DEBUG: "secondary",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "danger",
}

# Ensure messages persist across redirects using session storage
MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"


# Feature flags configuration
def load_feature_flags():
    """Load feature flags from configuration with defaults."""
    features = _bot_config.get("django", {}).get("features", {})
    return {
        "macro_preview": features.get("macro_preview", True),  # Default: enabled
    }


FEATURE_FLAGS = load_feature_flags()

# Logging configuration to show debug statements
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "macros": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "servers": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
