# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "uv" # Python dependencies via uv
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Only use released versions (stable releases)
    versioning-strategy: increase
    # Group related updates together
    groups:
      production-dependencies:
        patterns:
          - "discord.py"
          - "pyyaml"
          - "aiofiles"
          - "django*"
          - "djangorestframework"
      development-dependencies:
        patterns:
          - "pytest*"
          - "ruff"
          - "sphinx*"
          - "pre-commit"
    # Allow both minor and patch updates for stable packages
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions" # GitHub Actions
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # GitHub Actions automatically use released versions only
    open-pull-requests-limit: 5
