# Generated by Django 5.2.6 on 2025-09-08 23:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiscordGuild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guild_id",
                    models.CharField(
                        help_text="Discord guild ID", max_length=20, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Discord guild name", max_length=100),
                ),
                (
                    "icon_url",
                    models.URLField(blank=True, help_text="Discord guild icon URL"),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="First time we recorded this guild",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time guild info was updated"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DiscordUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        help_text="Discord user ID", max_length=20, unique=True
                    ),
                ),
                (
                    "username",
                    models.CharField(help_text="Discord username", max_length=32),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, help_text="Discord display name", max_length=32
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, help_text="Discord avatar URL"),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="First time we recorded this user",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time user info was updated"
                    ),
                ),
            ],
            options={
                "ordering": ["username"],
            },
        ),
        migrations.CreateModel(
            name="DiscordChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        help_text="Discord channel ID", max_length=20, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Discord channel name", max_length=100),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Channel"),
                            ("voice", "Voice Channel"),
                            ("category", "Category"),
                            ("news", "News Channel"),
                            ("store", "Store Channel"),
                            ("thread", "Thread"),
                            ("forum", "Forum Channel"),
                        ],
                        default="text",
                        help_text="Type of Discord channel",
                        max_length=20,
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="First time we recorded this channel",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time channel info was updated"
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="user_stats.discordguild",
                    ),
                ),
            ],
            options={
                "ordering": ["guild__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="StatisticsCollectionJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_range_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days to look back (null = all time)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the collection job",
                        max_length=20,
                    ),
                ),
                (
                    "progress_current",
                    models.PositiveIntegerField(
                        default=0, help_text="Current progress"
                    ),
                ),
                (
                    "progress_total",
                    models.PositiveIntegerField(
                        default=0, help_text="Total items to process"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if job failed"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When job was created",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When job started running", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When job completed", null=True
                    ),
                ),
                (
                    "messages_processed",
                    models.PositiveIntegerField(
                        default=0, help_text="Total messages processed"
                    ),
                ),
                (
                    "users_updated",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of users updated"
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_jobs",
                        to="user_stats.discordguild",
                    ),
                ),
                (
                    "target_channels",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific channels to scan (empty = all channels)",
                        to="user_stats.discordchannel",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific user to collect stats for (null = all users)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_stats.discorduser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_messages",
                    models.PositiveIntegerField(
                        default=0, help_text="Total messages sent in this channel"
                    ),
                ),
                (
                    "messages_last_7_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Messages sent in last 7 days"
                    ),
                ),
                (
                    "messages_last_30_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Messages sent in last 30 days"
                    ),
                ),
                (
                    "messages_last_90_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Messages sent in last 90 days"
                    ),
                ),
                (
                    "first_message_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of first message", null=True
                    ),
                ),
                (
                    "last_message_date",
                    models.DateTimeField(
                        blank=True, help_text="Date of most recent message", null=True
                    ),
                ),
                (
                    "last_collected",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When these stats were last collected",
                    ),
                ),
                (
                    "collection_method",
                    models.CharField(
                        choices=[
                            ("full_scan", "Full Channel Scan"),
                            ("incremental", "Incremental Update"),
                            ("manual", "Manual Collection"),
                        ],
                        default="full_scan",
                        help_text="How these statistics were collected",
                        max_length=20,
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_stats",
                        to="user_stats.discordchannel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_stats",
                        to="user_stats.discorduser",
                    ),
                ),
            ],
            options={
                "ordering": ["-total_messages"],
                "unique_together": {("user", "channel")},
            },
        ),
    ]
