# Generated by Django 5.2.6 on 2025-09-15 01:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignableRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_id",
                    models.CharField(help_text="Discord role ID", max_length=20),
                ),
                (
                    "role_name",
                    models.CharField(
                        help_text="Discord role name (cached for display)",
                        max_length=100,
                    ),
                ),
                (
                    "role_color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Role color in hex format (e.g., #ff0000)",
                        max_length=7,
                    ),
                ),
                (
                    "is_self_assignable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether users can assign this role to themselves",
                    ),
                ),
                (
                    "requires_permission",
                    models.CharField(
                        choices=[
                            ("admin_only", "Administrators Only"),
                            ("moderators", "Moderators and Administrators"),
                            ("trusted_users", "Trusted Users and Above"),
                            ("everyone", "Everyone"),
                            ("custom_roles", "Custom Roles Only"),
                            ("server_owner", "Server Owner Only"),
                        ],
                        default="everyone",
                        help_text="Permission level required to assign this role",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this role was added to assignable list",
                    ),
                ),
                (
                    "added_by",
                    models.CharField(
                        help_text="Discord user ID who added this role", max_length=20
                    ),
                ),
                (
                    "added_by_name",
                    models.CharField(
                        default="",
                        help_text="Discord username who added this role",
                        max_length=100,
                    ),
                ),
                (
                    "server_config",
                    models.ForeignKey(
                        help_text="The server configuration this role belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignable_roles",
                        to="admin_panel.serverpermissionconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignable Role",
                "verbose_name_plural": "Assignable Roles",
                "ordering": ["role_name"],
                "unique_together": {("server_config", "role_id")},
            },
        ),
    ]
