# Generated by Django 5.2.6 on 2025-09-17 03:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0002_assignablerole"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("temperature", "Temperature Conversion")],
                        help_text="Type of event to configure",
                        max_length=50,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this event is enabled for the server",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional configuration options for this event (JSON format)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this event configuration was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this event configuration was last updated",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        help_text="Discord user ID who last updated this configuration",
                        max_length=20,
                    ),
                ),
                (
                    "updated_by_name",
                    models.CharField(
                        default="",
                        help_text="Discord username who last updated this configuration",
                        max_length=100,
                    ),
                ),
                (
                    "server_config",
                    models.ForeignKey(
                        help_text="The server configuration this event belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_configs",
                        to="admin_panel.serverpermissionconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Configuration",
                "verbose_name_plural": "Event Configurations",
                "ordering": ["event_type"],
                "unique_together": {("server_config", "event_type")},
            },
        ),
    ]
