name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**/*.py'
      - '.github/workflows/docs.yml'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**/*.py'
  # Allow manual triggering
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build documentation
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install Python and dependencies
      run: uv sync

    - name: Activate virtual environment and generate documentation
      run: |
        source .venv/bin/activate
        cd docs
        sphinx-apidoc -o api ../discord-bot --force --separate --no-toc
        sphinx-build -b html . _build/html

    - name: Upload documentation artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html

  # Deploy to GitHub Pages (only on main branch)
  deploy:
    # Only run on main branch pushes, not PRs
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
